/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '28/10/16 11:23' with Gradle 3.1
 *
 * @author luisb, @date 28/10/16 11:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
